apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMDEuMC4yMTYiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiQ2RpdHYxMjM0NSIsImF1dGgiOiJZV1J0YVc0NlEyUnBkSFl4TWpNME5RPT0ifX19
kind: Secret
metadata:
  name: harborsecret 
  namespace: kube-ops
type: kubernetes.io/dockerconfigjson
